name: Client

on:

  push:
    paths:
    - 'client/**'
    branches: 
    - main 
  
  pull_request:
    paths:
    - 'client/**'
    branches:
    - main
  
  workflow_dispatch:

jobs:

  verify-standards:

    name: Checking standards client pipeline
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2
