name: Client

on:
  push:
    paths:
      - "client/**"
    branches:
      - client

  pull_request:
    paths:
      - "client/**"
    branches:
      - client

  workflow_dispatch:

jobs:
  verify-standards:
    name: Checking standards client pipeline
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm install

      - name: Run linter
        run: |
          npm run lint
