name: Server 

on:

  push:
    paths:
    - 'server/**'
    branches: 
    - server 
  
  pull_request:
    paths:
    - 'server/**'
    branches:
    - server 
  
  workflow_dispatch:

jobs:

  verify-standards:

    name: Checking standards server pipeline
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      
      - name: Check if linter is applied
        run: |
          python -m black . --check
      
      - name: Run tests and print report
        run: |
          python -m coverage run -m pytest tests
          python -m coverage report -i
